version: '3'

services:
    db:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${ZZODB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${ZZOVLOG_DB_NAME}
            - MYSQL_USER=${ZZOVLOG_DB_USER}
            - MYSQL_PASSWORD=${ZZOVLOG_DB_PASSWORD}
        volumes:
            - ./db:/var/lib/mysql
            - ./db.conf.d:/etc/mysql/conf.d
    backend:
        build: ./backend
        environment:
            - ZZOVLOG_SECRET_KEY
            - ZZOVLOG_DEBUG
            - ZZOVLOG_DB_USER
            - ZZOVLOG_DB_PASSWORD
            - ZZOVLOG_DB_HOST
            - ZZOVLOG_DB_PORT
        ports:
            - "8000:80"
        depends_on:
            - db
    frontend:
        build: ./frontend
        ports:
            - "80:8080"
